services:
  mysql:
    image: mysql:8.0
    container_name: urlshortener-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortener
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - url_shortener_net

  redis:
    image: redis:6.2
    container_name: urlshortener-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - url_shortener_net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener-api
    ports:
      - "3000:3000"
    environment:
      - MYSQL_DSN=root:root@tcp(mysql:3306)/urlshortener?parseTime=true
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-secret-key
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - url_shortener_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: urlshortener-frontend
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - url_shortener_net

volumes:
  mysql_data:
  redis_data:

networks:
  url_shortener_net:
    driver: bridge 